# Singular Value Decomposition (SVD)
##  What is SVD?

**SVD (Singular Value Decomposition)** is a mathematical technique to **decompose any matrix** into three simpler matrices that reveal important structure about the data.

The formula is:

$$
A = U \Sigma V^T
$$

---

## Meaning of Each Term

| Symbol | Name | Intuition |
|:--------|:------|:-----------|
| $A$ | Original matrix | The data or system we start with |
| $U$ | Left singular vectors | Basis directions for the rows |
| $\Sigma$ | Singular values | Strength or importance of each direction |
| $V^T$ | Right singular vectors | Basis directions for the columns |

---

## Intuitive Understanding

SVD finds **new coordinate axes** where your matrix looks as simple as possible (no correlation between features).

- $V^T$ → rotates data to align with axes of maximum variance  
- $\Sigma$ → scales along those axes (like stretching)  
- $U$ → rotates again to the output space  

> In short: SVD turns any transformation into a simple “stretch + rotate” process.

---
|  Application |  Description |
|:----------------|:----------------|
| **PCA (Principal Component Analysis)** | PCA uses SVD internally to find directions of maximum variance |
| **Image Compression** | Keep only the top singular values to reconstruct an image efficiently |
| **Noise Reduction** | Remove small singular values to eliminate low-energy noise |
| **Recommendation Systems** | Used in matrix factorization (e.g., Netflix, Spotify) |

In [7]:
import numpy as np

A = np.array([[3, 1, 1],
              [-1, 3, 1]])

# Compute SVD
U, S, VT = np.linalg.svd(A)

print("U:\n", U)
print("\nΣ (Singular values):\n", S)
print("\nV^T:\n", VT)

U:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Σ (Singular values):
 [3.46410162 3.16227766]

V^T:
 [[ 4.08248290e-01  8.16496581e-01  4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  8.59279716e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]


In [9]:
# Convert S (vector) into diagonal matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:len(S), :len(S)] = np.diag(S)

# Reconstruct A
A_reconstructed = U @ Sigma @ VT
print("\nReconstructed A:\n", A_reconstructed)


Reconstructed A:
 [[ 3.  1.  1.]
 [-1.  3.  1.]]
